draw_set_font(global.creditsfont)
draw_set_halign(fa_left)
draw_set_valign(fa_top)
if (currentfont == global.bigfont)
	draw_text(x, y, "Current font: bigfont")
if (currentfont == global.creditsfont)
	draw_text(x, y, "Current font: creditsfont")
if (currentfont == global.smallfont)
	draw_text(x, y, "Current font: smallfont")
if (currentfont == global.smallfont2)
	draw_text(x, y, "Current font: font_small")
if (currentfont == global.smallnumberfont)
	draw_text(x, y, "Current font: smallnumber_fnt")